### ISSUE TITLE
recorded MIDI Files are all corrupt!

### ISSUE THREAD

**Issue by knopserl** [icalvo/Icm.MidiRecorder#16]
First of all, I like the solution & concept. Exactly what we need for our church to record from E-Piano as well as from Organ.
The program starts and is detection all MIDI adapters and inputs. Detects powered on MIDI devices and starts autosensing, showing correct MIDI events and starts saving after the delay time.
However, all recordings are corrupt and cant be opened with MIDI programs for playback.
If I use other MIDI Recorder Apps (with GUI) the recordings are ok.
I also observe, that it saves two MIDI files. I start it with the default parameter.
Any idea want is wrong? Is this a bug?
I have installed the required .NET FW (6.x).

**Comment by icalvo** [comment]
Can you attach here one of those midi files? Also, what OS are you using?

**Comment by knopserl** [comment]
> Can you attach here one of those midi files? Also, what OS are you using?

Here are a couple of recorded MIDI files from an MIDI E-Piano.
Recorded with another MIDI Recorder with GUI, everything is ok, but I need your utility for background recording.
One thing which I have seen is the log output shows always a negative length value, but note and vol is ok.

I'm using Windows 10 22H2 64Bit.
[MIDI_recording.zip](https://github.com/MidiRecorder/MidiRecorder/files/14073322/MIDI_recording.zip)

**Comment by icalvo** [comment]
@knopserl I am able to read them. They are MIDI files Type 1, that may be an issue if your program is trying to open them as Type 0. I am using [Bandlab Cakewalk](https://www.bandlab.com/products/cakewalk), which is a free, full-fledged DAW.

I know the issue about the length. I'll add an issue for that.

**Comment by knopserl** [comment]
> @knopserl I am able to read them. They are MIDI files Type 1, that may be an issue if your program is trying to open them as Type 0. I am using [Bandlab Cakewalk](https://www.bandlab.com/products/cakewalk), which is a free, full-fledged DAW.
> 
> I know the issue about the length. I'll add an issue for that.

Thanks for looking at my problem.
You're right, I've tried with other apps and they can open it. It's strange, that files contain quite a long period of no MIDI events. I thought the recording will only start, if there are events and stop after the default (5sec) or a specified delay time

**Comment by icalvo** [comment]
I'll close this one as the files can be indeed opened. All other related issues are being solved with #17.
